### ISSUE TITLE
Dynamic Fields

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#1]
## Context

Currently, `ProcedureModel` contains a defined set of fields (see `src/models/procedureModel.js`). There are 4 types of fields:
- date
- text (1 line)
- textarea (multiline)
- choicetree

The type of each field is known and used directly by the views (see `src/views/procedureEntryView.html`).
## Task

We need to allow a `ProcedureModel` to contain a dynamic list of fields, whose types can be defined by the user. A global and persistant `ProcedureTemplate` will store the list of fields as a list of:
- unique id
- type (one of the 4 mentioned above)
- short description (free text)

When a new ProcedureModel is created, a copy of the global template is store into the new ProcedureModel. This copy of the template is used when displaying the Procedure.

A new screen, `TemplateEditor`, will be introduced to edit the global template. It will allow to add new fields, or remove existing fields.
## Notes

The following fields cannot be removed from the global template:
- name
- procedure
- date

**Comment by elmigranto** [comment]
**What we have**
- `ProcedureModel` with fixed fields;
- Logbookr app for editing list of `ProcedureModel`s (basically UI for `ProceduresCollection`?).

**What we would like** is to allow each instance of `ProcedureModel` to hold customizable properties. To do that we create `FieldModel` with something like:

``` js
{ id: 'string',    // uuid()
  type: 'string',  // one of ['text', 'textarea', 'date', 'choicetree']
  name: 'string',  // backbone's field name (for instance.get())
  description: 'string' }
```

To use custom fields in procedure, user can (required to?) create desired `[FieldModel]`, save it as `TemplateModel` with `id`, `name` and `description` and select that template when creating a new procedure. Custom fields will then be displayed as fillable inputs according to their type.

**Some questions**
- About "Notes". Where those fields belong? Isn't `name` and `procedure` fields are the same thing? Don't we store everything inside `ProcedureModel` and `Template` is just list of fields with description?
- Why global template? Are we going to allow only one for the whole app? Why not just define model with fields we want then. I am feeling that what required when adding new procedure is for user to select procedure template and fill in fields according to that template.
- Why copy template over to `ProcedureModel`, if we care only about fields? Or do we just store template id and retrieve it for displaying procedure, what if it gets deleted/modified?

<hr/>

_I am not sure about correctness of backbone-related terms used, hope you can judge whether I am getting things correctly._

**Comment by j3k0** [comment]
> Logbookr app for editing list of ProcedureModels (basically UI for ProceduresCollection?).

And a UI for ChoiceTree.

> [...] create desired [FieldModel], save it as TemplateModel

A Template could actually be a Collection of FieldModel.

> About "Notes". Where those fields belong?

Before the user did anything, the global template should already contain the existing fields. Most fields can be removed, except those 3. I'll get back to this after those other answers.

> Isn't name and procedure fields are the same thing?
- `name` is the firstname + surname of the patient (a free text)
- `procedure` is the type of procedure (a choicetree)

> Don't we store everything inside ProcedureModel and Template is just list of fields with description?

Yes. Template will just be a list of fields with descriptions. Procedure will be a list of fields, with descriptions and values.

> Why global template? Are we going to allow only one for the whole app?

Yes.

> Why not just define model with fields we want then. I am feeling that what required when adding new procedure is for user to select procedure template and fill in fields according to that template.

No need to select which template to use, there's just 1 global template.

When adding a new procedure it will be initialized with the list of fields from the global template, without values... the procedureEntryView will allow to fill values.

> Why copy template over to ProcedureModel, if we care only about fields?

Because we may edit the global template after having stored some procedures. We want the procedure to be a snapshot of the template (+ values for each field), at the time the procedure was created.

> Or do we just store template id and retrieve it for displaying procedure, what if it gets deleted/modified?

Cf answer above, non-issue if the procedure contains a snapshot of the template at procedure creation time. This snapshot will be used by the procedureEntryView

**more on non-removable fields**

The procedureView uses the procedure's `name`, `procedure` and `date`, to show an overview of the procedure. This is why those 3 fields cannot be removed from the template.

**Comment by elmigranto** [comment]
### View embedding

Since we have dynamic fields, I feel that there should be a view for rendering just one field and we'll use that inside procedure's view. (With possible exceptions for things like photos and some wrappers around date.) Though I didn't find the way to do that in Backbone that I am happy with, any suggestions?

**Comment by elmigranto** [comment]
Some random things that I find concerning:
- There are a lot of javascript involved. Like 400 lines for displaying single Procedure… Doesn't look fun :)
- Though we have separate `test` folder (test app itself) that's probably meant to be independent of `src`, there is stuff like `Collection`s bound to local storage that should probably be application's concern.

What's the final thing is? Is it just webapp to drop into `WebView` or more like server-client talking?

**Comment by elmigranto** [comment]
Woa, those turned out to be really random things :) I can't quite get a full picture in my head of how things work yet.

**Comment by j3k0** [comment]
### Big picture

The final thing is a mobile app that has no link to a server, works offline, only uses localStorage. This "logbookr" is included as a submodule in the full project (only `src` is used, `test` folder ignored by the full project). It's fine if "logbookr" is hard-linked with localStorage, as we most likely wont' include a server in the equation anytime soon (if ever).

If you're interested, I can give you access to the full app.

### Subviews

Yes, using a subview for each field could be cleaner, even though BackboneJS doesn't excel in doing that. I recently found out about "marionettejs" a framework that extends backboneJS. They happen to define among other things a "CompositeView" which it meant to do what you need.

Nicely of them, they even provide part of the feature separately: https://github.com/marionettejs/backbone.babysitter

### Too much JS

Feel free to refactor whatever you find "not fun" :) The cleaner code, the better!

### test folder

`test` is just here to check that `src` is working fine. `src` should be providing all the required features. From what I remember, you shouldn't have to change anything in `test` folder to add the new features. Actually, you'd better not change anything in `test` folder: the module's external interface should stay the same, so it doesn't break the full app.
