### ISSUE TITLE
Textarea Field Type

### ISSUE THREAD

**Issue by elmigranto** [j3k0/logbookr#10]
Should not be `input type="text"`, but rather an actual `textarea`.

**Comment by j3k0** [comment]
Should be a textarea. this is for longer, multi-lines texts.

**Comment by j3k0** [comment]
**Small (but important) bug**
1. Enter `aie caramba</textarea>let's break da html!` as a value in the textarea field.
2. Save
3. Textarea is now broken.

**To fix**

Textarea's value needs to be escaped. Trick: use `<%-` instead of `<%=` to escape html.
