### ISSUE TITLE
Import legacy data

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#12]
User already using the app from a couple of month have data stored in the pre-custom-field format.  Such data should not be lost, but converted to the new format by the application when detected.

See app at commit 98e5847cbdd9028739e3a276d64c1d8210903fbf for the legacy data format.

This applies to both procedures and choiceTrees.

**Comment by elmigranto** [comment]
Do you have some example data we can test this on. Would be nice to have real examples, especially for photos.

**Comment by j3k0** [comment]
Right. Actually you can create some test data by doing a checkout of 98e5847, clean up local storage from your chrome dev tools, then run the app.

**Comment by elmigranto** [comment]
Would it be ok to prefix all the new data with something like `v2`? Or maybe add `version` to each model.

**Comment by j3k0** [comment]
Or maybe add a global `version` string stored on the phone (default to "1.0" if not specified).

At startup, we can check `version`, upgrade the data as required, update `version`. So the upgrade module can be something external from the rest.

Do as you find best, it just has to work.

**Comment by elmigranto** [comment]
I don't believe choice tree format has changed (I didn't make any modifications myself at least). So this is only applicable to procedures format, correct?

**Comment by j3k0** [comment]
Yes I think so as well, only convert legacy procedures to the new format.

**Comment by elmigranto** [comment]
Okay, I decided to prefix all the data with "schema" version. Currently I basically rename everything that is not `ProcedureModel` to `v2.<old-key>` and save a copy to `v2.safekeep.<old-key>`.

Procedures are converted to current format with `diagnostic`, `supervision`, `senior`, `stage`, `comment` as template fields:

``` js
diagnostic: parsed.diagnostic,
supervision: parsed.supervision,
senior: parsed.senior,
stage: parsed.stage,
comment: parsed.comment,
fields: [
  {name: 'diagnostic', description: 'Diagnostic', type: 'text'},
  {name: 'supervision', description: 'Supervision', type: 'choicetree'
  {name: 'senior', description: 'Senior', type: 'choicetree'},
  {name: 'stage', description: 'Stage', type: 'choicetree'},
  {name: 'comment', description: 'Comment', type: 'textarea'}
]
```

Other fields map directly to our `requiredFields` (`date`, `type`, `patient`). Except for `photos` (#16).

``` js
date: parsed.date,
type: parsed.type,
patient: parsed.patient,
photos: [],
// requiredFields: toFieldsJson(toFields([
//   {name: 'date', description: tr('FieldModel.required.date'), type: FieldModel.types.DATE},
//   {name: 'type', description: tr('FieldModel.required.type'), type: FieldModel.types.CHOICETREE},
//   {name: 'patient', description: tr('FieldModel.required.patient'), type: FieldModel.types.TEXT},
//   {name: 'photos', description: tr('FieldModel.required.photos'), type: FieldModel.types.PHOTOS}
// ])),
```

`id` stays the same, sorting will be based on `parsed.date`.

**Comment by elmigranto** [comment]
It probably is required to add `Description -> Name` mapping in the templates to match things from `fields` and set default template to contain those fields.

**Comment by j3k0** [comment]
You are right. The default template should include the fields that used to be in the v1 of the application (those present in legacy data).

**Comment by j3k0** [comment]
Checked initial implementation, seems alright, didn't test for real yet.

It's a good idea to store a `safekeep`, I wonder if the safekeep shouldn't just be the original data with its original key.

Doing so would allow the user to revert to an older version of the app and keep seeing the data.

`shouldConvert` would then have to check if a `v2` version of the data exists (don't updade if there's already an upgraded version).

**Comment by elmigranto** [comment]
If user removes something in a new version, it will still be in the old format in LS. We would have to come up with a way to remember which keys were converted.

I assume the app is on AppStore? Is it even possible to downgrade there?

**Comment by j3k0** [comment]
Yes, if anything is changed in the new format, the old format is not changed, that's fine: it's just here for failure recovery, right?

Downgrading an app is possible on iOS and Android (using iTunes for the first, downloading an older APK for the second).

**Comment by elmigranto** [comment]
Correct. Though if you delete procedure and restart the app, it will find old version, but not new one, and convert it again. So we'll need to work that out first.

Ok.

**Comment by j3k0** [comment]
Right for the deletion issue. Instead of judging by the existence of `v2.xxx` to know if upgrade is necessary, you can create a `v1.upgraded` key.

**Comment by elmigranto** [comment]
Removed safekeep; instead, it keeps original, but remembers that it was converted.

**Comment by j3k0** [comment]
All good. Little change was the procedure's `type` had a choicetree named `procedure`. Fixed with https://github.com/j3k0/kodoc-apps/commit/965a1a659798de18386d8f1f8a5d408cee548104
