### ISSUE TITLE
Photos (converting old things to new format and camera.js)

### ISSUE THREAD

**Issue by elmigranto** [j3k0/logbookr#16]
Currently camera.js returns random stuff.

We need to change old code to new structure and come up with a way to convert existing pictrues to new field type "photos".

**Comment by elmigranto** [comment]
**taking photo**

Currently we have `camera.takePicture(callback)`, I don't think it'll change much. Looks pretty straight forward.

**displaying pictures**

Most of the stuff in camera.js is currently handled (like legend, show/remove photo, basically, everything dom-related). I'm not sure what `<image>`'s `src` attribute is, judging by the code, it will be `file://` urls we just put there?

``` js
// Called when a photo is successfully retrieved
onPhotoDataSuccess: function(imageURI) {
    var that = this;
    _.defer(function() {
        /*that.$(".responsive-procedure-picture")[0].src = imageURI;
        that.$(".procedure-picture-thumbnail")[0].src = imageURI;
        that.$(".procedure-picture-thumbnail").attr("image-url", imageURI).removeClass("hidden");*/
        that.movePic(imageURI);
    });
},
```

**converting old procedures**

I'm a bit lost here… Is it working at all, if so, can you give an example of what will be in local storage?

**Comment by j3k0** [comment]
In localStorage for pictures you just have URIs (`file://` style), so it should just work like a text input.

**Comment by elmigranto** [comment]
I've looked through a code, if I got it right, old procedures could have onlu 1 photo defined within `picture` attribute as File URI.

**Comment by j3k0** [comment]
Yes that's right.

**Comment by elmigranto** [comment]
Ok, `picture` is converted to new format, `camera.js` _should_ work. I'll try to test it under cordova's `browser` target, if I am able to build this thing again…

**Comment by elmigranto** [comment]
I've built it, but instead of taking a picture, camera plugin streams webcam video, guess it is not ready for `browser` target. I'd try to fiddle with it, but I don't really think that would be time well spent.

**Comment by j3k0** [comment]
Yes, don't waste time: I'll do the testing. There's a chat server waiting for your golden fingers as well ;)

**Comment by j3k0** [comment]
Fix implemented in kodocs-app.
