### ISSUE TITLE
ProcedureEntryView Back Button

### ISSUE THREAD

**Issue by elmigranto** [j3k0/logbookr#3]
After opening ChoiceTree editor, back button stops working:
1. Add/Edit procedure
2. Click any choicetree field, so popover shows up
3. Close popover
4. `< Back` does not work anymore

**Comment by elmigranto** [comment]
It also looks like this has something to do with double adding of new procedure:
1. Click Add
2. Pick value for a choice tree twice
3. Click Save
4. You have 2 procedures added, one is empty

**upd** It seems necessary to click `< Back` somewhere in the process.

**Comment by elmigranto** [comment]
`< Back` situation is same in master, so that might be some bug in test app. Looking into…

**Comment by elmigranto** [comment]
Okay, `< Back` stops working because it does `this.view.back()` in test app's `router.js` and when we open choice tree, its view saved as `this.view` of a router. That can't be right, since popover can't go back, it can only be hidden. So what I suggest is that we change router's `goBack` to call `this.mainView.goBack()` instead of `this.view.goBack()`.

`this.view` — reference to last rendered view;
`this.mainView` — reference to last rendered view within `#tab-content`;
`this.popoverView` — references to last rendered view within `#popover`.

**Comment by j3k0** [comment]
Yes for the change, indeed a bug specific to this test app, my bad!

**Comment by elmigranto** [comment]
I'm unable to reproduce second part about saving procedure twice. However, with changes made it'll throw an error from [here](https://github.com/j3k0/logbookr/blob/procedure-dynamic-fields/src/models/procedureModel.js#L83). There some time 2 events for `save-procedure` click, and I can not quite pinpoint where…

**Comment by j3k0** [comment]
A quick fix could just be to `_.debounce` the event handler.

``` js
myEvent: _.debounce(function(e) {
...
},  50, true)
```
