### ISSUE TITLE
Photos

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#4]
Photos will be a special type of field: `photos`

The value in a procedure will be an array of pictures' url + legend for each.

Code is meant to be run in a cordova app, for browser testing the `takePicture` method could just be calling the success callback with url of a random picture from the internet. `if (root.cordova) ...` is a valid test to check if the app runs on cordova.

**Comment by elmigranto** [comment]
Is there any way to test within cordova env without building stuff for phone?

**Comment by j3k0** [comment]
Yes, cordova has a "browser" target. Never explored that though

**Comment by j3k0** [comment]
Some doc here: http://www.raymondcamden.com/2014/09/24/Browser-as-a-platform-for-your-PhoneGapCordova-apps

As said earlier, if you're not willing to dig into cordova as well, you can simply do a browser-testing mode by returning a random picture url... The cordova picture taking code should be working, or can be fixed later on.

**Comment by elmigranto** [comment]
It worked! Not quite sure how to organize code so we will not need to copy sources and deps under cordova-app since it does not support symlinks. Maybe move everything into cordova project?

Anyways, moving that for later, will do with random internet pictures for now.

**Comment by j3k0** [comment]
You could either move everything into a cordova project or have a cordova `before_prepare` hook that copy over files into the right location. See https://cordova.apache.org/docs/en/edge/guide_appdev_hooks_index.md.html

**Comment by elmigranto** [comment]
Okay, you can check this out and see whether it is what you had in mind and what you would like to change (except being able to take actual photos :)

**Comment by j3k0** [comment]
This is exactly it.

Clicking "delete" should be followed by some confirmation dialog, as it can be hit by mistake...

Nothing else, good job :+1:

**Comment by elmigranto** [comment]
My reasoning for no confirmation on delete was that unless you hit save, it is all good, and clicking "Back" will not remove photo. But you are probably right, because some other changes might be there which user would like to preserve. Will update.

**Comment by j3k0** [comment]
BTW, I'm thinking `back` should do `save` as well.
- it prevents forgetting to hit `save`
- nowadays, modern UIs tends to autosave changes
  - template editor is already doing autosave

Easy change if I'm right: just call the `save()` event from the view's `goBack()`.

**Comment by elmigranto** [comment]
Might as well ditch cloning all together and save directly to original procedure.

**Comment by j3k0** [comment]
Well, I was wrong: `save` and `cancel` is still the way to go.

**Comment by elmigranto** [comment]
Ok, no changes here except photo deletion confirmation?

**Comment by j3k0** [comment]
Yes

**Comment by elmigranto** [comment]
If we would like to not lose changes on "Back", we can do something like that: when we swap view's model, we check its id, If `clone.id == newModel.id`, we can skip resetting our clone. This way changes won't be saved to local storage until "Save" is clicked, but unsaved changes won't be lost on "Back".

Thought this might be confusing… User accidentally clicks Back, returns to edit the same procedure, sees changes are there and assumes they are saved.

Maybe simple notification about unsaved changes when leaving the page would do just fine.

**Comment by j3k0** [comment]
I'm opening a new issue to discuss that, will comment from there. Let's finish with v2.0 this change will be an improvement for v2.1
