### ISSUE TITLE
Pagination and search by patient name

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#6]
Make sure proceduresView is paginated (at most N=50 procedures per page)

Add a search field that filters results based on the patient name. Conception note: keep in mind that more advanced search based on other fields may be added later.

**Comment by elmigranto** [comment]
I'd say we switch from raw local storage to something like WebSQL (which is SQLite in webkit-based browsers). At the first glance, there is:
— free paging, powerful search;
— webkit and [cordova](http://cordova.apache.org/docs/en/5.0.0/cordova_storage_storage.md.html#Storage) supported (I assume that is what final app will use);
— [backbone plugins](https://github.com/MarrLiss/backbone-websql).

Most plugins I found are quite old, but should be enough to start with.

**Comment by j3k0** [comment]
The view can also be provided with the full collection + a page number, then slice the array when rendering the template.

Advanced search can be implemented using `collection.filter` (identical to [_.filter](http://underscorejs.org/#filter)), which is as powerful, if not more than SQL.

**Comment by j3k0** [comment]
The idea being that if we can prevent refactoring again, that would be good.

Also, I had some not-so-good experience with Backbone + SQLite.

**Comment by j3k0** [comment]
Instead of pagination, this would be a better solution: https://github.com/puppybits/BackboneJS-PerfView 

They claim 60fps on mobile browsers with 100,000 models.

Would you like to take a look? Seems relatively straightforward.

**Comment by elmigranto** [comment]
> 60fps on mobile browsers with 100,000 models.

Sounds impressive, though I don't really see how is that useful in real application. What is the point to render that in any way, performant or not, no one is going to scroll through that. Also, try pressing <kbd>End</kbd> on their benchmark page.

Same thing goes for pagination, no one will ever click through hundreds of pages.

I feel that showing couple of filters on the main page (like "Most recently added" and "Recently viewed") and implementing functional search would be more useful thing to spend time on.

**Comment by j3k0** [comment]
Ok. Anyway as it's important to deliver this soon, so let's go to the quickest solution: no paging, show all procedures without the above plugin. Let's consider our power user has at most 300 of them, we'll test on mobile if there's any perf issue.

**Comment by j3k0** [comment]
I just tested the search feature, is it done? I had some weird behaviors?

For your reference:
- I have 2 procedures for patients called `Harry Potter` and `Harry Jones`
  - Searching `Harry` just return 1 result
- I have 1 procedure for patient called `JC`
  - Searching `J` returns no result
  - Searching `JC` returns 1 result
- I have 1 procedure for patient called `qwq`
  - Search `q` returns 1 result
  - etc (works as expected, unlike `JC`)

**Comment by elmigranto** [comment]
> I just tested the search feature, is it done? I had some weird behaviors?

I was wrongly thinking that jquery allowed or-ing possible attribute values in selector via `|`, so when multiple results were found, it wasn't showing anything at all. Fixed that.

I also "dumbed down" search function so it uses `String.indexOf()` instead of `RegExp.test()`, since it would be less error-prone and pretty much what is required.
