### ISSUE TITLE
Recreate Identical Field's Name

### ISSUE THREAD

**Issue by j3k0** [j3k0/logbookr#7]
_As a user that deleted a template's field by mistake, I wan't to be able to recreate the exact same field in the template._

I think a solution would have template's `name` be a hash of the template's `description`. Good one [here](http://stackoverflow.com/questions/7616461/generate-a-hash-from-string-in-javascript-jquery).

**Comment by elmigranto** [comment]
Don't see how hashing description would allow undoing deletion — user will still have to retype field's description. We can either add "Undo" command which will recreate last deleted field, or mark fields `deleted`/`disabled` rather than removing them from template collection and allowing to re-enable them at any point in the future.

Probably worth adding deletion confirmation too (like in #5).

**Comment by j3k0** [comment]
OK, let's just do delete confirmation for now.

For reference, the scenario was:
1. In the template, I have a field which description is `Hospital` (choicetree).
2. I add some procedures for which I fill the hospital (and create some values for hospital's choicetree)
3. I later remove hospital from the template, because I think I don't need it, and go on with my life.
4. 3 days later I realize I in fact needed to store the hospital for my procedures, I re-create a field which description is `Hospital`.
5. I add some procedures for which I fill the hospital.

Would be nice that the `Hospital` field created in `4` has the same field-name as the one in `1`. What's nice about that:
- for procedures created in `5` I also get the choicetree values created in `2`.
- for a later stage advanced search feature, if I filter using the `Hospital` field, there's only one such field.

A major issue with that, if I rename a field, it's suddenly not the same field anymore.

**Comment by elmigranto** [comment]
Okay, I see. Maybe field names should be editable after all. It would also allow the ability to bind 2 different fields to the same tree (like with the Hospital example, you can initially go to one hospital but get redirected to another one, or something like that).

We can still generate unique attribute name (the key under which it'll be stored).

**Comment by elmigranto** [comment]
So what do we do with this? Just stop at notification for now?

**Comment by j3k0** [comment]
Well, a delete confirmation is a good start.

Re-creating a field with a previously existing description is a case that can be handled later. But to make that possible let's at least store a map "description => name" for eventual later use.

**Comment by elmigranto** [comment]
> store a map "description => name" for eventual later use.

I'm not sure what you mean. Let's say I create `chocicetree` field with a description `Fruit`, it gets named `some-hash`. Then I add some fruit choices and delete the field, choice tree itself is still there and we'd like new field described as `Fruit` (and named `some-other-hash`) to be using that choice tree. So rather than selecting choice tree by field name we would want to select then by field description, basically change: `openChoiceTree(field.name)` to `openChoiceTree(field.description)`.

**Comment by j3k0** [comment]
That's not what I meant.

My idea was:
1. We have a map, let's call it `nameForDesc`, that is persistant (localStorage).
2. We create a field with name `some-hash` and a description `Fruit`
3. We store the relation : `nameForDesc["Fruit"] = "some-hash"`

When we create or rename a field with `description`, we can check in `nameForDesc` if there's already a `name` for it. Almost-pseudo code:

``` js
if (nameForDesc[description])
    name = nameForDesc[description];
else
    name = nameForDesc[description] = uuid();
```

**Comment by j3k0** [comment]
EDIT, to maintain an eventually existing name when renaming a field:

``` js
if (nameForDesc[description])
    name = nameForDesc[description];
else {
    if (!name)
        name = uuid();
    nameForDesc[description] = name;
}
```

**Comment by elmigranto** [comment]
Let's go over this one more time.

Fields in the template have `fieldName` and `fieldDescription`. They are bound to choice tree, and we currently save choice trees with `fieldName` as backbone model ID.

You suggesting is that we choose ID for choicetree not as `fieldName`, but the value on a new object keyed by `fieldDescription` with values being Choice Tree ID.

``` js
{ "fieldDescription": "choiceTreeId" }
```

Correct me if I'm wrong, this is exactly as using "fieldDescription" for choice tree IDs, except we map arbitrary text allowed as description to the result of `uuid()` via this new object. I don't see any problems with just using `fieldDesciprtion` as ID for now.

**Comment by elmigranto** [comment]
Both ways won't allow mapping different descriptions to the same choice tree without additional code, but latter one does not require storing `description -> id` map.

**Comment by j3k0** [comment]
Sorry, that's not it again.

I suggest we keep using `fieldName` exactly as we do now: a unique ID for the field, that can be used as a key for advanced filtering and to link to a choicetree.

What you suggest, using `fieldDescription` as an ID, wouldn't work: rename a field and you loose its meaning. In the general case, changing `fieldDescription` shouldn't change the ID, `fieldName`. 

An exception, the point of this issue, if a field has `fieldDescription` equal to this of a older field (see the `Hospital` example above), `fieldName` should be restored to what it was.

The `description -> id` map is a solution to remember the ID for old fields, given their description.

Let's forget mapping 2 fields to the same choicetree, this is not a requirement.

Makes sense?

**Comment by elmigranto** [comment]
> if a field has `fieldDescription` equal to this of a older field <…>, `fieldName` should be restored to what it was.

Okay, I think I understand now.

**Comment by j3k0** [comment]
Cool, I'm being confusing sometimes
