### ISSUE TITLE
Add New Field adds 2 fields instead of one

### ISSUE THREAD

**Issue by elmigranto** [j3k0/logbookr#9]
It actually does, huh… Ran under cordova-browser and got this.

**Comment by elmigranto** [comment]
And then it doesn't for some reason…

**Comment by j3k0** [comment]
Maybe some kind of special condition when view is added to the DOM that makes the click event handler being added twice... Could be an issue happening only with the demo app.

Let's keep that lower priority, eventually try to learn more if we stumble upon it again..

**Comment by elmigranto** [comment]
Okay. The reason is that `new Navigation` called every time when you click on `Logbook` link from `#home`. So multiple `Navigation` instances create multiple `Template` views which add to same collection multiple times. Test app thing, will fix later.

**Comment by elmigranto** [comment]
To reproduce:
1. open http://localhost:8080/test/index.html;
2. click `Logbook`;
3. click `< Back`;
4. click `Logbook`;
5. (optionally repeat 3 and 4);
6. try adding new field.

**Comment by j3k0** [comment]
Okay. I guess `Navigation` should be made a singleton to prevent multiple instances to be created no matter what.

**Comment by elmigranto** [comment]
This must be a case with `HomeView` as well.

**Comment by elmigranto** [comment]
This also fixes second part of #3 where it would insert multiple procedures.

**Comment by j3k0** [comment]
OK. No issues experienced here, I'm closing.
